### PR TITLE
implement reset RS Command

### PR DESCRIPTION
**Pull request by huzaifah0x00**
implement reset Command according to [MeCom Protocol Specification 5117C](https://www.meerstetter.ch/customer-center/downloads/category/19-mecom-communication-protocol-specifications)

### CODE REVIEW

**Comment by spomjaksilp** [comment]
@huzaifah0x00 did you test your implementation?

**Comment by timhellwig** [comment]
I did something similar a while ago but inheriting from Query instead of MeFrame to do it with less double code:



`
class RS(Query):

    """
    Implementing system reset.
    """
    _PAYLOAD_START = 'RS'

    def __init__(self, sequence=1, address=0, parameter_instance=1):
        """
        Create a query to set a parameter value.
        :param sequence: int
        :param address: int
        :param parameter_instance: int
        """
        
        # init header (equal for get and set queries)
        super(RS, self).__init__(parameter=None,
                         sequence=sequence,
                         address=address,
                         parameter_instance=parameter_instance)

        # no need to initialize response format, we want ACK`

It can be found in a branch i created to also support Laser diode drivers from Meerstetter here:

https://github.com/timhellwig/pyMeCom/tree/laser_diode_drivers

**Comment by huzaifah0x00** [comment]
@spomjaksilp i tested it with a [TEC 1091](https://www.meerstetter.ch/products/tec-controllers/tec-1091) and it worked as expected

**Comment by spomjaksilp** [comment]
@huzaifah0x00 thx for the contribution. I guess we can close this now since https://github.com/spomjaksilp/pyMeCom/pull/8  is merged now.

**Pull request closed without merging**
